[package]
name = "adaptarr"
version = "0.3.2"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "macros"]

[profile.dev]
lto = false

[profile.test]
lto = false

[dependencies]
actix = "0.7.9"
actix-web = "0.7.14"
adaptarr-macros = { path = "./macros" }
base64 = "0.10.0"
bitflags = "1.0.4"
blake2 = { version = "0.2.18", package = "blake2-rfc" }
bytes = "0.4.11"
cookie = "0.11.0"
diesel_migrations = "1.3.0"
env_logger = "0.6.0"
failure = "0.1.3"
fluent = "0.5.0"
fluent-bundle = "0.5.0"
fluent-syntax = "0.8.0"
futures = "0.1.25"
itertools = "0.8.0"
lazy_static = "1.2.0"
lettre = "0.9.0"
lettre_email = "0.9.0"
listenfd = "0.3.3"
magic = "0.12.2"
mime = "0.3.13"
minidom = "0.11.0"
native-tls = "0.2.3"
r2d2 = "0.8.3"
r2d2-diesel = "1.0.0"
rand = "0.7.0"
ring = "0.13.5"
rmps = { version = "0.13.7", package = "rmp-serde" }
rust-argon2 = "0.4.0"
sentry-actix = "0.15.4"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
structopt = "0.2.13"
tempfile = "3.0.5"
tera = "0.11.20"
termion = "1.5.1"
toml = "0.5.0"
unicode-width = "0.1.5"
url = "1.7.0"
zip = "0.5.0"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.diesel]
version = "1.4.0"
features = ["chrono", "postgres", "uuidv07"]

[dependencies.diesel-derive-enum]
version = "0.4.0"
features = ["postgres"]

[dependencies.log]
version = "0.4.6"
features = ["serde"]

[dependencies.uuid]
version = "0.7.0"
features = ["serde"]

[dependencies.sentry]
version = "0.15.4"
features = ["with_debug_to_log"]

[patch.crates-io]
fluent = { git = "https://github.com/katalysteducation/fluent-rs.git" }
fluent-bundle = { git = "https://github.com/katalysteducation/fluent-rs.git" }
fluent-syntax = { git = "https://github.com/katalysteducation/fluent-rs.git" }
