[package]
name = "adaptarr-server"
version = "0.0.0"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]

[dependencies]
actix-web = "0.7.14"
env_logger = "0.6.0"
failure = "0.1.3"
failure_derive = "0.1.3"
listenfd = "0.3.3"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.9"
