[package]
name = "adaptarr-server"
version = "0.0.0"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]

[workspace]
members = [".", "api-derive"]

[dependencies]
actix = "0.7.9"
actix-web = "0.7.14"
api-derive = { path = "./api-derive" }
base64 = "0.10.0"
bitflags = "1.0.4"
blake2-rfc = "0.2.18"
bytes = "0.4.11"
diesel_migrations = "1.3.0"
env_logger = "0.6.0"
failure = "0.1.3"
failure_derive = "0.1.3"
fluent = "0.5.0"
fluent-bundle = "0.5.0"
fluent-syntax = "0.8.0"
futures = "0.1.25"
lazy_static = "1.2.0"
lettre = "0.8.3"
lettre_email = "0.8.3"
listenfd = "0.3.3"
magic = "0.12.2"
minidom = "0.10.0"
r2d2 = "0.8.3"
r2d2-diesel = "1.0.0"
rand = "0.6.1"
ring = "0.13.5"
rmp-serde = "0.13.7"
rust-argon2 = "0.3.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
structopt = "0.2.13"
tempfile = "3.0.5"
tera = "0.11.20"
toml = "0.4.9"
zip = "0.5.0"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.diesel]
version = "1.3.3"
features = ["chrono", "postgres", "uuid"]

[dependencies.log]
version = "0.4.6"
features = ["serde"]

[dependencies.uuid]
version = "0.6.0"
features = ["serde"]

[patch.crates-io]
fluent = { git = "https://github.com/katalysteducation/fluent-rs.git" }
fluent-bundle = { git = "https://github.com/katalysteducation/fluent-rs.git" }
fluent-syntax = { git = "https://github.com/katalysteducation/fluent-rs.git" }
