[package]
name = "adaptarr-server"
version = "0.0.0"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]

[dependencies]
actix-web = "0.7.14"
base64 = "0.10.0"
chrono = "0.4.6"
diesel_migrations = "1.3.0"
env_logger = "0.6.0"
failure = "0.1.3"
failure_derive = "0.1.3"
lazy_static = "1.2.0"
listenfd = "0.3.3"
r2d2 = "0.8.3"
r2d2-diesel = "1.0.0"
rand = "0.6.1"
ring = "0.13.5"
rmp-serde = "0.13.7"
rust-argon2 = "0.3.0"
serde = "1.0.80"
serde_derive = "1.0.80"
structopt = "0.2.13"
tera = "0.11.20"
toml = "0.4.9"

[dependencies.diesel]
version = "1.3.3"
features = ["chrono", "postgres"]
