[workspace]
members = [
    "crates/error",
    "crates/i18n",
    "crates/macros",
    "crates/mail",
    "crates/util",
]

[patch.crates-io]
fluent-bundle = { git = "https://github.com/openstax-poland/fluent-rs.git" }
fluent-syntax = { git = "https://github.com/openstax-poland/fluent-rs.git" }
