[package]
name = "adaptarr-server"
version = "0.0.0"
authors = ["Krzysztof Mędrzycki <aiwenari@gmail.com>"]

[dependencies]
actix-web = "0.7.14"
chrono = "0.4.6"
diesel_migrations = "1.3.0"
env_logger = "0.6.0"
failure = "0.1.3"
failure_derive = "0.1.3"
listenfd = "0.3.3"
r2d2 = "0.8.3"
r2d2-diesel = "1.0.0"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.9"

[dependencies.diesel]
version = "1.3.3"
features = ["chrono", "postgres"]
