version: "3.5"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: docker
  adaptarr:
    build: .
    # image: docker.pkg.naukosfera.com/adaptarr-server:0.6.0
    command: bash -c "while ! </dev/tcp/db/5432; do sleep 2; done; /usr/bin/adaptarr server start"
    ports:
      - "8012:8080"
      # - "%(projects.adaptarr-server.port):80"
    # networks:
    #   - adaptarr
    configs:
      - source: adaptarr
        target: /var/lib/adaptarr/config.toml
    # secrets:
    #   - source: adaptarr-pgpass
    #     target: pgpass
    #     mode: 0600
    #   - source: adaptarr-secret
    #     target: server-secret
    volumes:
      - adaptarr-storage:/var/lib/adaptarr/storage
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    # environment:
    #   PGPASSFILE: /run/secrets/pgpass
  frontend:
    build: ./../adaptarr-front
    ports: ["8013:80"]

# networks:
#   adaptarr:

configs:
  adaptarr:
    name: config.toml
    # template: ./templates/config.toml

# docker-swarm specific
# secrets:
#   adaptarr-pgpass:
#     name: pgpass
#   adaptarr-secret:
#     name: secret

volumes:
  adaptarr-storage: