version: "3.5"

services:

  web:
    image: nginx:1.17.5
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: docker

  backend:
    build: .
    # wait for postgres
    command: bash -c "while ! </dev/tcp/db/5432; do sleep 2; done; /usr/bin/adaptarr server start"
    # ports: ["8012:8080"] # example: http://localhost:8012/api/v1/users/me
    configs:
      - source: adaptarr
        target: /var/lib/adaptarr/config.toml
    volumes:
      - adaptarr-storage:/var/lib/adaptarr/storage
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  frontend:
    build: ./../adaptarr-front
  
configs:
  adaptarr:
    name: config.toml

volumes:
  adaptarr-storage: