[package]
name = "adaptarr-macros"
version = "0.2.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.0"
quote = "1.0.0"
synstructure = "0.12.0"

[dependencies.syn]
version = "1.0.0"
features = ["full"]
