[package]
name = "adaptarr-macros"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.26"
quote = "0.6.11"
syn = "0.15.26"
synstructure = "0.11.0"
